services:
  - type: web
    name: cv-backend
    runtime: docker
    plan: free
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /api/health

  - type: web
    name: cv-frontend
    runtime: docker
    plan: free
    rootDir: frontend
    envVars:
      - key: NEXT_PUBLIC_API_URL
        fromService:
          type: web
          name: cv-backend
          property: host
      - key: PORT
        value: 10000
